modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/ShyNieke/MundaneRedstone/issues"
license="MIT"

[[mods]]
modId="mundaneredstone"
version="${file.jarVersion}"
displayName="Mundane Redstone"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mundane-redstone-ore"
authors="ShyNieke, Mrbysco"
description='''
Replacing Vanilla Redstone ore with non-shiny redstone since 2017
'''

[[dependencies.mundaneredstone]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[mixins]]
config = "mundaneredstone.mixins.json"