modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/ShyNieke/MundaneRedstone/issues"
license="MIT"

[[mods]]
modId="mundaneredstone"
version="${file.jarVersion}"
displayName="Mundane Redstone"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mundane-redstone-ore"
authors="ShyNieke, Mrbysco"
description='''
Replacing Vanilla Redstone ore with non-shiny redstone since 2017
'''

[[dependencies.mundaneredstone]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="BOTH"