modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://github.com/ShyNieke/MundaneRedstone/issues"
license="MIT"

[[mods]]
modId="mundaneredstone"
version="${file.jarVersion}"
displayName="Mundane Redstone"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mundane-redstone-ore"
authors="ShyNieke, Mrbysco"
description='''
Replacing Vanilla Redstone ore with non-shiny redstone since 2017
'''

[[dependencies.mundaneredstone]]
modId="minecraft"
mandatory=true
versionRange="[1.17.1,1.18)"
ordering="NONE"
side="BOTH"
[[dependencies.mundaneredstone]]
modId="forge"
mandatory=true
versionRange="[37.0.59,38)"
ordering="NONE"
side="BOTH"